### ISSUE TITLE
Make logged in user more visible

### ISSUE THREAD

**Issue by mberg** [onaio/collect#16]
Right now it's in the title but not on the home page.

**Comment by imwongela** [comment]
@rowo what would be appropriate place to show the logged in user and should it appear on all the screens?

**Comment by rowo** [comment]
@mberg what do you mean it's not on the home page? It's at the top in the title of every page, right?

**Comment by rowo** [comment]
I'm a hesitant to do anything that changes how ODK Collect currently works because I don't fully understand all of the scenarios with how our users and their teams use it (and review what competitors are doing). So my inclination is to move this to milestone 2 since that is a longer design process.
