### ISSUE TITLE
Option to choose ODK vs Ona Collect

### ISSUE THREAD

**Issue by rowo** [onaio/collect#21]
![screen shot 2015-11-23 at 1 47 28 pm](https://cloud.githubusercontent.com/assets/1584163/11346067/d0d2dd2c-91e8-11e5-8437-13fe1a581d69.png)

Getting this message on the Nov 23 apk. After selecting a Blank form to fill out.

**Comment by imwongela** [comment]
This can be resolved. I'll explicitly declare the Ona Collect to handle the form filling process. The system cannot determine the app to use because the intent was implicit.

**Comment by imwongela** [comment]
Solved by v2. Closing on this
