### ISSUE TITLE
Icon missing in "Complete action" dialog

### ISSUE THREAD

**Issue by rowo** [onaio/collect#23]
As reported by @cagulas: "Looks like we need an icon there."

![screenshot_2015-12-09-17-02-00](https://cloud.githubusercontent.com/assets/1584163/11700945/cc66b704-9e9a-11e5-92ad-8f6ab0ea974b.png)

**Comment by imwongela** [comment]
![screenshot_2015-12-17-11-53-00](https://cloud.githubusercontent.com/assets/13150523/11865463/409277d8-a4b5-11e5-9dd9-9368d2213d08.png)
This was introduced on removing the icon on the other screens. I have put it back so the form entry screen will have the icon.

**Comment by rowo** [comment]
ok
