### ISSUE TITLE
Log in credentials do not change on Android versions below 7.0

### ISSUE THREAD

**Issue by skambo** [onaio/collect#44]
### Software and hardware versions

V1.4.12 rev 1063 #42
Tested on Samsung J5 v5.1.1. and a Motorola with Android v6.0

### Problem description
- You can't change your log in account details, once you've logged in with one account.

### Steps to reproduce the problem
- Log in to Ona collect with your credentials on the `general_settings`
- Use / navigate through the app (optional)
- Go back to the general_settings and change the account details and reconnect to server
- Notice you still have forms from the account you just changed from, meaning the new log in credentials aren't recognized.

### Expected behavior

- Switching between accounts should be possible once correct log in credentials are submitted.

**Comment by jasonrogena** [comment]
This issue also affects ODK Collect. Collect only provides the username and password if the formList endpoint returns `dlauthrequired`. @ukanga When someone changes the username or password, is there a way of telling the endpoint to first invalidate the auth cookie (if there's one) and force reauth?
